package com.pmd.config;

import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.env.EnvironmentPostProcessor;
import org.springframework.core.Ordered;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.MapPropertySource;
import org.springframework.core.env.Profiles;

public class JwtSecretEnvPostProcessor implements EnvironmentPostProcessor, Ordered {

    private static final Logger logger = LoggerFactory.getLogger(JwtSecretEnvPostProcessor.class);
    private static final int MIN_SECRET_BYTES = 32;

    @Override
    public void postProcessEnvironment(ConfigurableEnvironment environment, org.springframework.boot.SpringApplication application) {
        String configuredSecret = readJwtSecret(environment);
        if (configuredSecret != null && !configuredSecret.isBlank()) {
            if (isValidSecret(configuredSecret)) {
                return;
            }
            if (!isDevProfile(environment)) {
                throw new IllegalStateException("PMD_JWT_SECRET must be at least 32 bytes (256 bits).");
            }
            logger.warn("PMD_JWT_SECRET is too short; auto-generating a dev-only secret for this run.");
            setGeneratedSecret(environment);
            return;
        }

        if (isDevProfile(environment)) {
            logger.warn("PMD_JWT_SECRET is not set; auto-generating a dev-only secret for this run.");
            setGeneratedSecret(environment);
            return;
        }

        throw new IllegalStateException("PMD_JWT_SECRET must be set and at least 32 bytes (256 bits).");
    }

    @Override
    public int getOrder() {
        return Ordered.HIGHEST_PRECEDENCE;
    }

    private static String readJwtSecret(ConfigurableEnvironment environment) {
        String secret = environment.getProperty("pmd.jwt.secret");
        if (secret == null || secret.isBlank()) {
            secret = environment.getProperty("PMD_JWT_SECRET");
        }
        return secret;
    }

    private static boolean isDevProfile(ConfigurableEnvironment environment) {
        return environment.acceptsProfiles(Profiles.of("dev", "local"));
    }

    private static boolean isValidSecret(String secret) {
        return secret.getBytes(StandardCharsets.UTF_8).length >= MIN_SECRET_BYTES;
    }

    private static void setGeneratedSecret(ConfigurableEnvironment environment) {
        byte[] bytes = new byte[MIN_SECRET_BYTES];
        new SecureRandom().nextBytes(bytes);
        String generated = Base64.getEncoder().encodeToString(bytes);
        Map<String, Object> props = new HashMap<>();
        props.put("pmd.jwt.secret", generated);
        environment.getPropertySources().addFirst(new MapPropertySource("pmdJwtSecretAutoGenerated", props));
    }
}
